---
- name: Prepare
  hosts: all
  tasks:
    - name: Install gnupg2
      apt:
        name: gnupg2
        state: present
    # The "ss" tool is needed by testinfra for socket inspection
    - name: Install ss
      apt:
        name: iproute2
        state: present
